server:
  port: 8401

spring:
  application:
    name: SpringCloud-Monitor-Admin
  boot:
    admin:
      ui:
        title: ${spring.application.name}
  security:
      user:
        name: kaleldo
        password: 123456